export const PROFILE_ROUTE = '/profile'
export const MESSAGE_ROUTE = '/message'
export const FINDUSERS_ROUTE = '/findusers'
export const MUSIC_ROUTE = '/music'
export const SETTINGS_ROUTE = '/settings'